env: "local"
log:
  level: "info"
jaeger: "localhost:14268"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "postgres"
  sslmode: "disable"
redis:
  addr: "localhost:6379"
  db: 0
grpc:
  host: "0.0.0.0"
  port: 44045
  timeout: 5s
premierliga:
  base_url: "https://api.premierliga.ru/api/getFullDataMatch"
  timeout: 5s
  retry_max_attempts: 3
  retry_base_interval: 200ms
