env: "local"
log:
  level: "info"
jaeger: "localhost:14268"
db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "postgres"
redis:
  addr: "localhost:6379"
  db: 0
grpc:
  host: "0.0.0.0"
  port: 44044
  timeout: 5s
airfare_cache_ttl: 30m
match_adapter:
  host: "localhost"
  port: 44045
  timeout: 3s
travelpayouts:
  base_url: "https://api.travelpayouts.com"
  currency: "rub"
  limit: 30
  timeout: 5s
