env: "local"
log:
  level: "info"
http:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 5s
  write_timeout: 15s
  shutdown_timeout: 5s
clients:
  airfare:
    address: airfare-provider:44044
    timeout: 5s
    retriesCount: 10
  match:
    address: match-adapter:44045
    timeout: 5s
    retriesCount: 10
defaults:
  origin_iata: "MOW"
jaeger:
  address: jaeger:14268
