env: "local"
log:
  level: "info"
http:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 5s
  write_timeout: 5s
  shutdown_timeout: 5s
clients:
  airfare:
    address: localhost:44044
    timeout: 5s
    retriesCount: 10
  match:
    address: localhost:44045
    timeout: 5s
    retriesCount: 10
jaeger:
  address: localhost:14268
